### ISSUE TITLE
No options passed in throws an error

### ISSUE THREAD

**Issue by marcelosomers** [mayo/metalsmith-serve#14]
I was trying to use the stock serve configuration:

``` js
...
.use(serve())
...
```

This basic config throws the following error:

``` shell
/Users/marcelo/development/metalsmith-v2/node_modules/metalsmith-serve/lib/index.js:101
    if (!options[key]) {
                ^

TypeError: Cannot read property 'cache' of undefined
    at /Users/marcelo/development/metalsmith-v2/node_modules/metalsmith-serve/lib/index.js:101:17
    at Array.forEach (native)
    at plugin (/Users/marcelo/development/metalsmith-v2/node_modules/metalsmith-serve/lib/index.js:100:25)
    at Object.<anonymous> (/Users/marcelo/development/metalsmith-v2/metalsmith.js:37:8)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

I'm on node v5.3.0.

I'm hoping this isn't just user error?

**Comment by mayo** [comment]
Hey @marcelosomers, I just added a test case for this, but it seems to work just fine. I noticed that line 101 where the errors was reported doesn't reflect what's on actual line 101, so maybe the version is slightly out of date with the code. I bumped the version and published a new npm package, so hopefully that will resolve things. It could also be node 5.x, as I only test on 4.x. Please let me know if version 0.0.7 works for you, and if not, I'll keep looking further.
