### ISSUE TITLE
Usage with metalsmith-watch?

### ISSUE THREAD

**Issue by ben-eb** [mayo/metalsmith-serve#2]
The readme recommends usage with metalsmith-watch, however when the watcher changes a file then metalsmith-serve tries to spawn a new server and crashes. The error output is this:

``` sh
[metalsmith-serve] serving /projects/test/build at http://localhost:8082
Started watching **/*
articles/hello-world.md was changed
[metalsmith-serve] serving /projects/test/build at http://localhost:8082

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)
```

And my configuration looks like this (the rest has been stripped for brevity):

``` js
var Metalsmith  = require('metalsmith'),
    serve       = require('metalsmith-serve'),
    watch       = require('metalsmith-watch');

Metalsmith(__dirname)
    .use(serve({
        port: 8082,
        verbose: true
    }))
    .use(watch())
    // ...
    .build(function(err) {
        if (err) { throw err; }
    });
```

I think this might be a bug in the code but I'm unsure of how to fix it. Any suggestions? :smile:

**Comment by micahgodbolt** [comment]
@mayo have things changed, or aren't process.env args supposed to go before the node command?

```
$ node build.js SERVE=1 
/ / Doesn't show up in process.env
```

```
$ SERVE=1 node build.js
/ / Shows up in process.env
```

**Comment by mayo** [comment]
This is shell specific. For example sh derived shells usually use the latter form, csh derived the former, etc.
